code/UkraineRestorationArchive/UkraineRestorationArchive.WEB/Controllers/BuildingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UkraineRestorationArchive.BLL;
using UkraineRestorationArchive.WEB.Models;
using System.Web.Mvc;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.IO;

namespace UkraineRestorationArchive.WEB.Controllers
{

    public class BuildingController : Controller
    {
        private readonly IImagesManager _imagesManager;
        private readonly ILogger<BuildingController> _logger;
        private static string BAddress;
        private static List<byte[]> photos;
        public BuildingController(ILogger<BuildingController> logger, IImagesManager imagesManager)
        {
            _imagesManager = imagesManager;
            _logger = logger;
            
        }
        public IActionResult Index(string address)
        {
            photos = _imagesManager.getImages(address);

            BAddress = address;

            return View(photos);
        }
        public ActionResult GetImage(int Id)
        {
            byte[] image = photos[Id];
            return File(image, "image/png");
        }
        [HttpPost]
        public ActionResult AddImage(IList<IFormFile> files)
        {
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    using (var reader = new StreamReader(file.OpenReadStream()))
                    {
                        byte[] buffer = new byte[file.Length];
                        var resultInBytes = ConvertToBytes(file);
                        Array.Copy(resultInBytes, buffer, resultInBytes.Length);

                        _imagesManager.addImage(User.Identity.Name, BAddress, buffer);
                    }
                }
            }
            return RedirectToAction("Index",new {address=BAddress });
        }
        private byte[] ConvertToBytes(IFormFile image)
        {
            using (var memoryStream = new MemoryStream())
            {
                image.OpenReadStream().CopyTo(memoryStream);
                return memoryStream.ToArray();
            }
        }
    }
}

code/UkraineRestorationArchive/UkraineRestorationArchive.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UkraineRestorationArchive.WEB.Models;

namespace UkraineRestorationArchive.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

code/UkraineRestorationArchive/UkraineRestorationArchive.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using Microsoft.Web.Helpers
@using Microsoft
<script src="~/Scripts/jquery-1.6.4.min.js" type="text/javascript"></script>

<div id='searchBoxContainer'><input type='text' id='searchBox' /></div>
<div id="myMap" style="position:relative; height:600px;"></div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    var map = null;

    function LoadMap() {
        map = new Microsoft.Maps.Map('#myMap', {
            credentials: "Ai-bVrBWh8aNMnAm1CAvIdnLBozHUA7B04ECxzUppg86Ql6XDSVtDFJ3VBVvEHCq",
            showTermsLink: false,
            center: new Microsoft.Maps.Location(50.4020355, 30.5326905),
            zoom: 6,
            mapTypeId: Microsoft.Maps.MapTypeId.aerial,
            showMapTypeSelector: false
        });
        Microsoft.Maps.loadModule('Microsoft.Maps.AutoSuggest', function () {
            var options = {
                maxResults: 4,
                map: map,
                countryCode: 'UA'
            };
            var manager = new Microsoft.Maps.AutosuggestManager(options);
            manager.attachAutosuggest('#searchBox', '#searchBoxContainer', selectedSuggestion);
        });
    }

    function selectedSuggestion(suggestionResult) {
        map.entities.clear();
        map.setView({ bounds: suggestionResult.bestView });
        var pushpin = new Microsoft.Maps.Pushpin(suggestionResult.location);
        Microsoft.Maps.Events.addHandler(pushpin, 'click', function () { clickPushpin(suggestionResult)  });
        map.entities.push(pushpin);
    }
    function clickPushpin(suggestRes) {
        var address = suggestRes.address.formattedAddress;
        //JSON data
        console.log(address);
        var urlquerstr = "@Url.Action("Index", "Building", new { address = "ADDRESS" })".replace("ADDRESS",address);
        window.open(urlquerstr);
    }
</script>
<script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>